language: scala
install:
  - curl -L https://github.com/google/protobuf/releases/download/v3.6.0/protoc-3.6.0-linux-x86_64.zip -o /tmp/protoc.zip
  - unzip /tmp/protoc.zip -d "$HOME"/protoc
  - mkdir -p "$HOME"/src && ln -s "$HOME"/protoc "$HOME"/src/protobuf
env:
  - PATH=$HOME/protoc/bin:$PATH
script:
  - sbt clean coverage test coverageReport package
after_success:
	- export CODECOV_TOKEN="aea4724f-2852-4c76-bf19-51d0adaf6f05"
	- bash < (curl -s https://codecov.io/bash)
